spring.datasource.url=jdbc:postgresql://localhost:5432/cpanalytics
spring.datasource.username=postgres
spring.datasource.password=cp123@pg

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080